### ISSUE TITLE
Implement requiresMainQueueSetup in RCTCardIOUtilities

### ISSUE THREAD

**Issue by Lukakva** [Kerumen/react-native-awesome-card-io#127] opened 2019-05-07 12:21 UTC
I'm using React Native 0.57.8. After building the project, I encountered this YellowBox warning

![image](https://user-images.githubusercontent.com/7294931/57298446-47713780-70e3-11e9-89e2-487f984da8bb.png)

I resolved this by adding the following code in ``/node_modules/react-native-awesome-card-io/ios/RCTCardIOUtilities.m``

![image](https://user-images.githubusercontent.com/7294931/57298656-c8c8ca00-70e3-11e9-975f-9ed4a46e6b0a.png)

This seemed a bit too small of an issue to be worthy of a pull request, so I'm creating an issue instead.

Thanks for the module and your work!

**Comment by Kerumen** [comment] 2019-05-25 16:42
@Lukakva Thanks for your issue, don't hesitate to open a PR I would happily merge it! :)

**Comment by Kerumen** [comment] 2020-09-24 12:45
This should be fixed in the last version! Don't hesitate to try it and to open a new issue if the problem is still there!

**Closed by Kerumen** 2020-09-24 12:45 UTC
