### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by lappalj4** [Kerumen/react-native-awesome-card-io#45] opened 2017-07-10 09:23 UTC
Getting the following error when trying to build the app: 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
  "_vImageBoxConvolve_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libRNCardIO.a(UIImage+ImageEffects.o)
  "_vImageMatrixMultiply_ARGB8888", referenced from:
      -[UIImage(ImageEffects) applyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in libRNCardIO.a(UIImage+ImageEffects.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Running on RN 0.45.1 & RN-awesome-card-io 0.6.4

What could be causing this?

**Comment by Kerumen** [comment] 2017-08-29 15:42
Do you still block on this? I'm sorry, I can't reproduce..

**Comment by Kerumen** [comment] 2017-09-23 11:24
Closing since the OP remains silent for one month.
Let me know if you still have problems and I can reopen :)

**Closed by Kerumen** 2017-09-23 11:24 UTC
Labels: bug
