### ISSUE TITLE
[ANDROID] Unable to pause activity error

### ISSUE THREAD

**Issue by gamezj** [Kerumen/react-native-awesome-card-io#8] opened 2016-09-24 21:56 UTC
I've been getting errors when I build for my Android simulator. 
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.test, PID: 2994
                  java.lang.RuntimeException: Unable to pause activity {com.test/com.test.MainActivity}: android.os.NetworkOnMainThreadException
                      at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3722)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3688)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3662)
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3636)
                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1472)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: android.os.NetworkOnMainThreadException
                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
                      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
                      at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
                      at okio.Okio$1.write(Okio.java:78)
                      at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
                      at okio.RealBufferedSink.emit(RealBufferedSink.java:178)
                      at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
                      at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
                      at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
                      at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeWebSocketQuietly(JSPackagerWebSocketClient.java:104)
                      at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeQuietly(JSPackagerWebSocketClient.java:98)
                      at com.facebook.react.devsupport.DevServerHelper.closePackagerConnection(DevServerHelper.java:129)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.reload(DevSupportManagerImpl.java:846)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.setDevSupportEnabled(DevSupportManagerImpl.java:481)
                      at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:490)
                      at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:504)
                      at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:110)
                      at com.facebook.react.ReactActivity.onPause(ReactActivity.java:60)
                      at android.app.Activity.performPause(Activity.java:6804)
                      at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
                      at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3711)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3688) 
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3662) 
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3636) 
                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1472) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 

**Additional Information**

React Native version: 0.34
Platform(s) (iOS, Android, or both?): Android
Operating System (macOS, Linux, or Windows?): MacOS

**Comment by Kerumen** [comment] 2016-09-24 22:35
Hum, you pasted a Runtime Error, these errors occurred at runtime not a compile time.
And I don't see any mention of the library in the stacktrace.
Are you sure that it's this library causing this issue?

**Comment by gamezj** [comment] 2016-09-24 23:59
Yes It's an example project with your library only

**Comment by Kerumen** [comment] 2016-09-25 10:09
Can you show me what are you trying to do? I cannot reproduce.

By the way, this library does not fit well to be tested in an emulator because it must have access to the camera, which an emulator lack.

**Comment by gamezj** [comment] 2016-09-25 11:24
export default class CardIO extends Component {
  componentWillMount() {
    if (Platform.OS === 'ios') {
      CardIOUtilities.preload();
    }
  }

  scanCard() {
    CardIOModule
    .scanCard()
    .then(card => {
      // the scanned card
    })
    .catch(() => {
      // the user cancelled
    })
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.scanCard}>
           <Text style={styles.welcome}>
              Scan card
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

When I click scan card button I got that error.

**Comment by Kerumen** [comment] 2016-09-25 13:34
It appears to be a bug related to React Native.

https://github.com/facebook/react-native/issues/10080

**Comment by Kerumen** [comment] 2016-10-18 16:22
[It was fixed in 0.35.](https://github.com/facebook/react-native/issues/10080#issuecomment-249663778) Feel free to reopen if you still encounter this issue!

**Closed by Kerumen** 2016-10-18 16:22 UTC
Labels: bug
